project:
  type: website
  output-dir: docs

website:
  favicon: images/heatmap_favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - blog.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



