project:
  type: website
  output-dir: docs

website:
  favicon: images/heatmap_favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - href: teaching.qmd
      #   text: Teaching
      # - blog.qmd
      # - about.qmd

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: false